ENV_PATH = 'D:\data\initData\env.xlsx'

CHROME_EXEC_PATH = 'C:\Program Files\Google\Chrome\Application\chrome.exe'   # 请改为你电脑内Chrome可执行文件路径
CHROME_EXTEND = ["wf-proxyIp","ffbceckpkpbcmgiaehlloocglmijnpmp","mcohilncbfahbmgdjkbpemcciiolgcge","yescap_v2.0.beta"]     # 扩展列表
CHROME_EXTEND_PATH = 'D:\data\etd\'
CHROME_USER_DATA_PATH = 'D:\data\cache\'        # 缓存目录
DEFAULT_OPEN_PAGE = []
DEFAULT_REMOVE_PAGE = []
