# 初始化环境文件
ENV_PATH = 'D:\data\initData\env.xlsx'
# 浏览器执行器
CHROME_EXEC_PATH = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
# 扩展目录
CHROME_EXTEND = ["wf-proxyIp","ffbceckpkpbcmgiaehlloocglmijnpmp","mcohilncbfahbmgdjkbpemcciiolgcge","yescap_v2.0.beta","bitlight"]
CHROME_EXTEND_PATH = 'D:\data\etd\'
# 缓存和用户数据，浏览器配置，浏览器下载地址
CHROME_USER_DATA_PATH = 'D:\data\cache\'
# 默认打开的页面
DEFAULT_OPEN_PAGE = []
DEFAULT_REMOVE_PAGE = []

# 钱包默认初始密码
WALLET_PASSWORD = "123qweasd"