# 初始化环境文件
ENV_PATH = 'D:\data\initData\env.xlsx'
# 线程数
THREAD_POOL_NUM = 2
# 浏览器执行器
CHROME_EXEC_PATH = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
# 扩展列表
CHROME_EXTEND = ["wf-proxyIp","ffbceckpkpbcmgiaehlloocglmijnpmp","okx","yescap_v2.0.beta","bitlight"]
# 工作目录
WORK_PATH = 'D:\python\wf-chrome\'
# 扩展目录
CHROME_EXTEND_PATH = 'D:\data\etd\'
# 缓存和用户数据，浏览器配置，浏览器下载地址
CHROME_USER_DATA_PATH = 'D:\data\cache\'
# 默认打开的页面
DEFAULT_OPEN_PAGE = []
# 不需要默认打开的页面，要移除
DEFAULT_REMOVE_PAGE = []
# 是否开启无头模式
HEADLESS = false
# 钱包默认初始密码
WALLET_PASSWORD = "123qweasd"
# 推特是否伪造
FAKE_TWITTER = true
GALXE_CAMPAIGN_IDS = [
    "GCzqctkqub"

]